version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
    depends_on:
      - zookeeper

  api:
    image: opensdsio/multi-cloud-api
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/localtime:/etc/localtime
      - /var/log/multi-cloud:/var/log/multi-cloud
      - ./examples/multi-cloud.conf:/etc/multi-cloud/multi-cloud.conf
    ports:
      - 8089:8089
    environment:
      - MICRO_SERVER_ADDRESS=:8089
      - MICRO_REGISTRY=mdns
      - OS_AUTH_AUTHSTRATEGY=keystone
      - OS_AUTH_URL=http://10.10.3.151/identity
      - OS_USER_DOMIN_ID=Default
      - OS_USERNAME=multi-cloud
      - OS_PASSWORD=opensds@123

  s3api:
    image: opensdsio/multi-cloud-s3api
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/localtime:/etc/localtime
      - /var/log/multi-cloud:/var/log/multi-cloud
      - ./examples/multi-cloud.conf:/etc/multi-cloud/multi-cloud.conf
    ports:
      - 8090:8090
    environment:
      - MICRO_SERVER_ADDRESS=:8090
      - MICRO_REGISTRY=mdns
      - OS_AUTH_AUTHSTRATEGY=keystone
      - OS_AUTH_URL=http://10.10.3.151/identity
      - OS_USER_DOMIN_ID=Default
      - OS_USERNAME=multi-cloud
      - OS_PASSWORD=opensds@123
      - OS_PROJECT_NAME=service

  backend:
    image: opensdsio/multi-cloud-backend
    environment:
      - MICRO_REGISTRY=mdns
      - DB_HOST=datastore:27017
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/log/multi-cloud:/var/log/multi-cloud
      - ./examples/multi-cloud.conf:/etc/multi-cloud/multi-cloud.conf

  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"

  s3:
    image: opensdsio/multi-cloud-s3
    environment:
      - MICRO_REGISTRY=mdns
      #- DB_HOST=datastore:27017
      - DB_HOST=tidb:4000
      # 0 means use user defined storage class, otherwise use default storage class.
      - USE_DEFAULT_STORAGE_CLASS=1
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/log/multi-cloud:/var/log/multi-cloud
      - ./s3/pkg/conf:/etc/multi-cloud
      - ./s3/pkg/datastore/yig/conf/:/etc/yig
      - /etc/ceph:/etc/ceph
      - ./examples/multi-cloud.conf:/etc/multi-cloud/multi-cloud.conf
    depends_on:
      - redis
      - tidb

  dataflow:
    image: opensdsio/multi-cloud-dataflow
    environment:
      - MICRO_REGISTRY=mdns
      - DB_HOST=datastore:27017
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - LIFECYCLE_CRON_CONFIG=0 0 0 * * ?
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/log/multi-cloud:/var/log/multi-cloud
      - ./examples/multi-cloud.conf:/etc/multi-cloud/multi-cloud.conf
    depends_on:
      - zookeeper
      - kafka
      - s3

  datamover:
    image: opensdsio/multi-cloud-datamover
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/localtime:/etc/localtime
      - /var/log/multi-cloud:/var/log/multi-cloud
      - ./examples/multi-cloud.conf:/etc/multi-cloud/multi-cloud.conf
    environment:
      - MICRO_REGISTRY=mdns
      - DB_HOST=datastore:27017
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      # PARTSIZE for multi-part migration, should not be less than 5(MB) or more than 100(MB)
      - PARTSIZE=5
      # JOB_MAX_RUN_TIME for each migration job, should not be less than 60(seconds) or more than 2592000(seconds)
      - JOB_MAX_RUN_TIME=86400
      # For lifecycle, if object need to be moved from one place to another, how long this moving can continue, should
      # not be less than 60(seconds) or more than 2592000(seconds).
      - OBJECT_MOVE_TIME=3600
    depends_on:
      - zookeeper
      - kafka

  datastore:
    image: mongo
    ports:
      - 27017:27017

  tidb:
    image: pingcap/tidb:v2.1.16
    container_name: tidb
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./s3/tidbconf/tidb.toml:/tidb.toml:ro
      - ./tidb_data:/tmp/tidb
    command:
      - --store=mocktikv
      - --config=/tidb.toml
      - -L=info

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./s3/pkg/conf/tidb.sql:/s3.sql
      - ./s3/pkg/datastore/yig/conf/yig.sql:/yig.sql
    command: mysql -h tidb  -P 4000 -u root -e "create database if not exists s3 character set utf8;use s3;source /s3.sql;create database if not exists yig character set utf8;use yig;source /yig.sql;"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - tidb
